### ISSUE TITLE
not running 

### ISSUE THREAD

**Issue by brainless3178** [gwen001/cloudflare-origin-ip#2]
Hi i **added** api and secret key still shwoing **error** 

**Error: 'CENSYS_UID' not defined**
To fix this:
export CENSYS_UID= 
export CENSYS_SECRET=

**Comment by gwen001** [comment]
Sorry but it works perfectly for me. I can't reproduce your problem.

You can find your API key and secret in you Censys account page:
<img width="587" alt="Screenshot 2023-01-18 at 11 00 11" src="https://user-images.githubusercontent.com/5347721/213142387-fa382585-3ffb-4ca7-8491-9de8da0639ea.png">

**Comment by brainless3178** [comment]
> Sorry but it works perfectly for me. I can't reproduce your problem.
> 
> You can find your API key and secret in you Censys account page: <img alt="Screenshot 2023-01-18 at 11 00 11" width="587" src="https://user-images.githubusercontent.com/5347721/213142387-fa382585-3ffb-4ca7-8491-9de8da0639ea.png">

Hey Thanks for reply back  i already paste my secret key and api key also but still got error 

Thanks
