### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by MMzF7** [gwen001/cloudflare-origin-ip#5]
[+] 5 ips added
[+] 2 unique ips collected
[+] Performing reference request...
Status=200, Length=2894, Headers=13, Content-Type=text/html; charset=utf-8
[+] Testing bypass...
172.67.195.141 is CloudFlare
[-] 170.187.131.209: HTTPSConnectionPool(host='170.187.131.209', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992)')))
[ cloudflare-origin-ip]$

**Comment by gwen001** [comment]
Port 443 might be closed on remote host.
