### ISSUE TITLE
Getting these errors

### ISSUE THREAD

**Issue by MANAVGK2038** [gwen001/cloudflare-origin-ip#7]
pool.map( partial(testBypass3,t_multiproc,r_reference,host), t_ips )
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
 line 313, in testBypass3
    if is_cloudflare3( IPAddress(ip) ):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 line 247, in is_cloudflare3
    ip = IP2Int( str(ip) )
         ^^^^^^^^^^^^^^^^^
], line 132, in IP2Int
    o = list( map(int, ip.split('.')) )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2606:4700:10::6814:4dc5'

**Comment by gwen001** [comment]
Looks like IPv6 format is not supported. I'll keep that for later.
Thanks.

**Comment by gwen001** [comment]
Should work for ipv6 now.
