### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by 666light** [gwen001/cloudflare-origin-ip#9]
[-] error occured: CENSYS_UID or CENSYS_SECRET not found, Censys removed from sources
[-] error occured: SECURITY_TRAILS_API_KEY not found, SecurityTrails removed from sources

add shodn too ,please update

**Comment by zol9527** [comment]
@666light You need to get api key and id in those websites.

**Comment by gwen001** [comment]
As the error says, you need api keys for those services, they are free.

Shodan is not in my plan for now but could be a good idea.

Thanks.
